In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r'D:\MSAIM\trimister-2 msaiml\Adv-Machine_learning\ReinforcementLearning\model_based_rl_dataset - model_based_rl_dataset.csv')
df.head()

Current State (Row, Col) Action Next State (Row, Col)  Reward
0                   (0, 3)     Up                (0, 3)      -5
1                   (0, 0)  Right                (0, 1)      -1
2                   (2, 2)   Down                (3, 2)      -1
3                   (0, 4)   Left                (0, 3)      -1
4                   (0, 0)   Down                (1, 0)      -1

In [3]:
df.shape

(300, 4)

In [5]:
# Create a 5x5 grid
grid = np.zeros((5, 5))

# Define start and goal positions
start = (0, 0)
goal = (4, 4)

# Mark some cells as obstacles
obstacles = [(1, 1), (2, 2), (3, 3)]
for obstacle in obstacles:
    grid[obstacle] = -1

# Mark start and goal positions
grid[start] = 1
grid[goal] = 2

print(grid)

[[ 1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
